### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by otonari726** [Pokerlishao/LoopGaussian#3]
Thank you for your great work!

I am very interested in your excellent work, but I have some concerns regarding the licensing. Could you please add a license?

**Comment by Pokerlishao** [comment]
Hi~

Thank you for your interest in my work and for raising this important point. I've added an MIT License to the repository. You can now use, modify, and distribute the code under the terms of this license.

If you have any other questions or need further clarifications, please feel free to ask.

Best regards,
